#!/usr/bin/env python

import subprocess

import edsimage


def build_image(repo, tag):
    image_name = '%s:%s' % (repo, tag)
    dir_name = '%s/%s' % (tag, repo)
    status = subprocess.call(['docker', 'build', '-t', image_name, dir_name])


for tag in edsimage.TAGS:
    for repo in edsimage.REPOS:
        build_image(repo, tag)
